name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Notes
        uses: actions/checkout@v2
        with:
          repository: mszturc/notes
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Print folder structure
        run: ls