name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Notes
        uses: actions/checkout@v2
        with:
          repository: mszturc/notes
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout Obsidian Reveal Template
        run: git clone https://mszturc:${{ secrets.ACCESS_TOKEN }}@github.com/mszturc/obsidian-reveal-template
      - name: Move Template to parent directory
        run : mv obsidian-reveal-template/* .
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup reveal-md
        run: npm install -g mszturc/reveal-md
      - name: Print folder structure
        run: ls
      - name: Generate Slides
        run: reveal-md ./ -w --glob 'deck-*.md' --static public